import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../../styles/Home.module.css'
import NavBar from './components/NavBar';

const Index: NextPage = () => {
  return (
    <>
      <Head>
        <title>Welcome to {process.env.NEXT_PUBLIC_NAME}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container py-3">
        <header>
         <NavBar/>

          <div className="pricing-header p-3 pb-md-4 mx-auto text-center">
            <h1 className="display-4 fw-normal">Welcome</h1>
            <p className="fs-5 text-muted">Test coloquio</p>
          </div>
        </header>

      </div>

    </>
  )
}

export default Index
