import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import NavBar from '../../components/NavBar';


const InvestmentCreate: NextPage = () => {
  return (
    <>
      <Head>
        <title>New Investment | {process.env.NEXT_PUBLIC_NAME}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container py-3">
        <header>
          <NavBar />

          <div className="pricing-header p-3 pb-md-4 mx-auto text-center">
            <h1 className="display-4 fw-normal">Create Investment</h1>
          </div>
        </header>

      </div>

    </>
  )
}

export default InvestmentCreate
