import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'


const InvestmentCreate: NextPage = () => {
  return (
    <div>
      <Head>
        <title>New Investment | {process.env.NEXT_PUBLIC_NAME}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


    </div>
  )
}

export default InvestmentCreate
